### ISSUE TITLE
rm2fb for version 3.6

### ISSUE THREAD

**Issue by juanfcocontreras** [timower/rM2-stuff#21]
It seems that there is a new version of Remarkable (3.6)

Would it be possible to update rm2fb to work with this version?

Thanks in advance!

**Comment by jilyaluk** [comment]
I'm looking into that.

3.6 firmware significantly differs from 3.5 (glibc version, damage update notifications in xochitl), this might take some time to adapt.

**Comment by timower** [comment]
Yeah, looks like they changed how they do updates. Using `QRegion` more, though the underlying functions didn't change that much.
I'll try to get it working, does the glibc version influence `LD_PRELOAD`?

**Comment by ReemX** [comment]
Hey there ReemX here part of the rmHacks team we currently are in the midst of releasing a revision of ddvk's hacks currently we got lamy pen, show brush icon instead of default "eye" icon, remove x from top right. a lot of users don't want to update to the latest versions because they use rm2fb on an older version thus making us want to update rm2fb to the latest version I stumbled upon this revision of the buffer upon researching the subject... What would you need in order to get an update going? we currently hold some tools that may help you in updating the buffer... this is my discord: reemx44

**Comment by timower** [comment]
Adding support for 3.6 can be done, I think I figured out how. Though it's not my focus right now, as toltec won't work yet.
That's blocked by https://github.com/toltec-dev/toolchain/pull/27, once that lands I'll focus on adding rm2fb support for 3.6

**Comment by ReemX** [comment]
alright, thanks for your work👌

**Comment by timower** [comment]
The dev branch just got 3.8 support: https://github.com/timower/rM2-stuff/tree/dev
I assume the latest version is OK?
